### PR TITLE
Few customization options

### PR DESCRIPTION
**Pull request by cemerson**
I know just enough to make some tweaks here - no pressure on accepting the merge just thought I'd send the changes your way for your review/consideration. I added the following to the config.js:

- exports.filePerSong 
- exports.filePerSongPrefixArtistName 
- exports.filePerSongPrefixAlbumName 
- exports.filePerSongUseAlbumFolders 

Also also append the Track Number to the lyric text file when using the filePerSong option.

### CODE REVIEW

**Review by Visual917 — COMMENTED** [review]
Thank you for making a contribution. I am going to review this in the morning, when I wake up and hopefully merge it if everything works as intended.

**Comment by cemerson** [comment]
Cool. Apologies if my additions are clean/efficient as they could be. Love this tool btw - thank you for creating it! 🙏🏻 FWIW I'm using to (hopefully) speed up getting lyric txt files into my Plex server.

**Comment by Visual917** [comment]
I am really glad it was good use for you. I initially wrote it for my friend for his AI lyrics writing app :) I am not home right now but will get to it ASAP

**Comment by Visual917** [comment]
Merged! Couldn't test it very thoroughly as I am really busy. Thanks again.

**Comment by cemerson** [comment]
Cool.

 

BTW do you know anything about LRC files – lyrics with timestamps in them? I wonder if there are any ways to automate/generate those kind of files. This (manual) tool - https://www.lrcgenerator.com/ -  is pretty slick but you have to listen to the whole song and click the button for each new line of lyrics – painful at scale obviously. There are of course plenty of other more feasible features to add to this tool – but LRC would be nice to incorporate at some point if/when possible.  Later.

**Comment by Visual917** [comment]
Oh yeah, could be.

**Pull request merged**
